# Generated by Django 5.0.6 on 2024-06-18 18:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=256)),
                ('sequence_no', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='username')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='name')),
                ('role', models.CharField(choices=[('USER', 'User'), ('ORGANIZER', 'Organizer')], default='USER', max_length=20)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('phoneNumber', models.PositiveBigIntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('year', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_activities', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizing_batch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desc', models.CharField(blank=True, max_length=256, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_cards', models.IntegerField(default=0)),
                ('total_polling_cards', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('sequence_no', models.IntegerField(default=1)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='apis.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desc', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(default='SURVEY_INPUT', max_length=32)),
                ('total_questions', models.IntegerField(default=0)),
                ('to_be_shown', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=60))),
                ('sequence_no', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_answers', to=settings.AUTH_USER_MODEL)),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.option')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('type', models.CharField(choices=[('SHORT_ANSWER', 'short_answer'), ('PARAGRAPH', 'paragraph'), ('NUMBER', 'number'), ('RADIO', 'radio'), ('DATE', 'date'), ('MULTIPLE_CHOICE', 'multiple_choice'), ('FILE', 'file'), ('CHECKBOXES', 'checkboxes'), ('URL', 'url'), ('IMAGE', 'image'), ('TIME', 'time'), ('EMAIL', 'email')], default='SHORT_ANSWER', max_length=64)),
                ('desc', models.CharField(blank=True, max_length=256, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('sequence_no', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.card')),
                ('users', models.ManyToManyField(related_name='user_questions', through='apis.Answer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options', to='apis.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.question'),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_cards', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('NOT_ATTEMPTED', 'Not Attempted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_ATTEMPTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.activity')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='users',
            field=models.ManyToManyField(related_name='participating_activities', through='apis.UserActivity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_activities', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('NOT_ATTEMPTED', 'Not Attempted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_ATTEMPTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.batch')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='users',
            field=models.ManyToManyField(related_name='participating_batch', through='apis.UserBatch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_questions', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('NOT_ATTEMPTED', 'Not Attempted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_ATTEMPTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.card')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='users',
            field=models.ManyToManyField(related_name='participating_cards', through='apis.UserCard', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('card', 'sequence_no'), name='unique_card_sequence_no'),
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(fields=('question', 'sequence_no'), name='unique_question_sequence_no'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('user', 'question', 'option')},
        ),
        migrations.AddConstraint(
            model_name='useractivity',
            constraint=models.UniqueConstraint(fields=('activity', 'user'), name='unique_activity_user'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(fields=('batch', 'name', 'sequence_no'), name='unique_batch_name_sequence'),
        ),
        migrations.AlterUniqueTogether(
            name='userbatch',
            unique_together={('user', 'batch')},
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('name', 'year')},
        ),
        migrations.AddConstraint(
            model_name='usercard',
            constraint=models.UniqueConstraint(fields=('card', 'user'), name='unique_card_user'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('activity', 'sequence_no'), name='unique_activity_sequence_no'),
        ),
    ]
