# Generated by Django 5.0.6 on 2024-06-17 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_user_created_at_alter_user_updated_at_batch_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbatch',
            unique_together={('user', 'batch')},
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desc', models.CharField(blank=True, max_length=256, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_cards', models.IntegerField(default=0)),
                ('total_polling_cards', models.IntegerField(default=0)),
                ('to_be_shown', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('sequence_no', models.IntegerField(default=1)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='apis.batch')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_cards', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('NOT_ATTEMPTED', 'not attempted'), ('IN_PROGRESS', 'in progress'), ('COMPLETED', 'completed')], default='NOT_ATTEMPTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.activity')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('activity', 'user')},
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='users',
            field=models.ManyToManyField(related_name='participating_activity', through='apis.UserActivity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('batch', 'name', 'sequence_no')},
        ),
    ]
