# Generated by Django 5.0.6 on 2024-06-17 19:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_userbatch_unique_together_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='to_be_shown',
        ),
        migrations.AlterField(
            model_name='batch',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='status',
            field=models.CharField(choices=[('NOT_ATTEMPTED', 'Not Attempted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_ATTEMPTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='userbatch',
            name='status',
            field=models.CharField(choices=[('NOT_ATTEMPTED', 'Not Attempted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_ATTEMPTED', max_length=20),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desc', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(default='SURVEY_INPUT', max_length=32)),
                ('total_questions', models.IntegerField(default=0)),
                ('to_be_shown', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=60))),
                ('sequence_no', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.activity')),
            ],
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_questions', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('NOT_ATTEMPTED', 'Not Attempted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_ATTEMPTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.card')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('card', 'user')},
            },
        ),
        migrations.AddField(
            model_name='card',
            name='users',
            field=models.ManyToManyField(related_name='participating_cards', through='apis.UserCard', to=settings.AUTH_USER_MODEL),
        ),
    ]
